feat: add tests, builds, and deployments to the app
Mohamad-Kamar/full-stack-app-ex-9 pull request #3
Opened 2021-12-02 17:24 UTC by Mohamad-Kamar

## Description:
The pull request includes the code for setting up pipelines on CicleCI and deploying the code to Heroku.

## Instructions for QA:
One this branch is pushed to master, the added config file is used by Circle CI to run Building and testing tasks on it.
Heroku is also configured to automatically deploy any changes to the main branch into the staging pipeline.
The "prod-start" and "heroku-postbuild" are what make it possible.

### Screenshots:
The screenshot below shows that the build and test pipelines succeed for this branch as it has a config file, but fail for the main branch.
![image](https://user-images.githubusercontent.com/72454341/144472018-e5850dd8-c867-477a-9e80-b22df455bc40.png)

2021-12-13 06:40 UTC, marounmelhem requested changes
Great work @Mohamad-Kamar! Also, awesome job on setting up a staging environment as well. 
A few small changes and this should be good to go.

2021-12-13 06:40 UTC, marounmelhem commented on .gitignore
> +/.env
Please add a `.env.example` file including all `.env` variables as empty (this file should be commited)

2021-12-13 06:40 UTC, marounmelhem commented on .circleci/config.yml
> +      - run: npm install
use `yarn` for consistency, also applies to the below `test` job

2021-12-14 20:28 UTC, Mohamad-Kamar commented on .gitignore
> +/.env
The only environment variable currently available in the files is set in the app.js file, and it is being used for Circle CI configs (it is committed with the rest of the changes).
Will make sure to provide such examples in the follow up PRs.

2021-12-14 20:35 UTC, Mohamad-Kamar commented on .circleci/config.yml
> +      - run: npm install
Addressed in [this commit](https://github.com/Mohamad-Kamar/full-stack-app-ex-9/pull/3/commits/f7cf239fd2c0268d185423735da54a57dd085fa1)

2021-12-15 11:00 UTC, marounmelhem commented on .gitignore
> +/.env
Having only 1 variable in your `.env` file doesn't mean you shouldn't add an `.env.example`. Let's add one and please make sure not to resolve conversations yourself. The reviewer should resolve it if the change has been addressed and validated.

2021-12-15 11:49 UTC, Mohamad-Kamar commented on .gitignore
> +/.env
What I meant is that there is no variable set in the my version of .env file itself. 
There is a file called app.json that sets an environment variable for hiroku to use. (I mentioned in my previous comment that it was for CircleCI, which was wrong).

I added an example env file, which will take effect on src/shared/config.js if implemented in an env file.

2021-12-21 07:56 UTC, marounmelhem approved these changes

2021-12-21 09:23 UTC, merged